name: Push Docker Image with Latest Tag
on:
  push:
    branches:
    - '**'

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Add latest tag to existing Docker image
      run: |
        IMAGES=$(grep image docker-compose.yml | awk -F' ' '{print $2}'|grep exastro|sed -e 's/${ITA_VERSION:-//' -e 's/${PLATFORM_VERSION:-//' -e 's/}//')

        for image in ${IMAGES}; do
          docker buildx imagetools create --tag ${image%:*}:latest ${image}
          exit 0
        done